package ai.shreds.shared.value_objects;

import java.math.BigDecimal;
import java.util.Objects;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;

/**
 * Value object representing monetary amount with currency.
 * Enhanced with Jakarta Bean Validation annotations as per UML specifications.
 */
public record SharedMoneyValue(
    @DecimalMin("0.0") @Digits(integer = 10, fraction = 2) BigDecimal amount,
    @NotBlank @Pattern(regexp = "^[A-Z]{3}$") String currency
) {

    /**
     * Compact constructor to enforce domain invariants.
     */
    public SharedMoneyValue {
        Objects.requireNonNull(amount, "Amount must not be null");
        if (amount.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Amount must be non-negative");
        }
        if (amount.scale() > 2) {
            throw new IllegalArgumentException("Amount must have at most two decimal places");
        }
        Objects.requireNonNull(currency, "Currency must not be null");
        if (!currency.matches("^[A-Z]{3}$")) {
            throw new IllegalArgumentException("Currency must be a valid ISO 4217 code");
        }
    }

    /**
     * Returns string representation of the money value.
     */
    @Override
    public String toString() {
        return amount + " " + currency;
    }

    /**
     * Equals method (automatically generated by record).
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null || getClass() != other.getClass()) return false;
        SharedMoneyValue that = (SharedMoneyValue) other;
        return Objects.equals(amount, that.amount) && Objects.equals(currency, that.currency);
    }

    /**
     * HashCode method (automatically generated by record).
     */
    @Override
    public int hashCode() {
        return Objects.hash(amount, currency);
    }
}
