package ai.shreds.shared.value_objects;

import java.util.Objects;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

/**
 * Value object representing a postal address.
 * Enhanced with proper Jakarta validation annotations.
 */
public record SharedAddressValue(
    @NotBlank @Size(max = 100) String street1,
    @Size(max = 100) String street2,
    @NotBlank @Size(max = 50) String city,
    @Size(max = 50) String state,
    @NotBlank @Size(max = 20) String postalCode,
    @NotBlank @Pattern(regexp = "^[A-Z]{2}$") String country
) {
    /**
     * Compact constructor to ensure required fields are non-null.
     */
    public SharedAddressValue {
        Objects.requireNonNull(street1, "street1 must not be null");
        Objects.requireNonNull(city, "city must not be null");
        Objects.requireNonNull(postalCode, "postalCode must not be null");
        Objects.requireNonNull(country, "country must not be null");
    }
    
    /**
     * Returns string representation of the address.
     */
    @Override
    public String toString() {
        return street1 + 
               (street2 != null && !street2.isBlank() ? ", " + street2 : "") + 
               ", " + city + 
               (state != null && !state.isBlank() ? ", " + state : "") + 
               ", " + postalCode + 
               ", " + country;
    }

    /**
     * Equals method (automatically generated by record).
     */
    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        if (other == null || getClass() != other.getClass()) return false;
        SharedAddressValue that = (SharedAddressValue) other;
        return Objects.equals(street1, that.street1) &&
               Objects.equals(street2, that.street2) &&
               Objects.equals(city, that.city) &&
               Objects.equals(state, that.state) &&
               Objects.equals(postalCode, that.postalCode) &&
               Objects.equals(country, that.country);
    }

    /**
     * HashCode method (automatically generated by record).
     */
    @Override
    public int hashCode() {
        return Objects.hash(street1, street2, city, state, postalCode, country);
    }
}
