version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: orderdb

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0

  activemq:
    image: rmohr/activemq:5.18.3

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - activemq